version: '3'

volumes:
  volume-shared:

services:

  settings-tp-0:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-0
    expose:
      - 4004
    command: settings-tp -vv --connect tcp://validator-0:4004

  settings-tp-1:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-1
    expose:
      - 4004
    command: settings-tp -vv --connect tcp://validator-1:4004

  settings-tp-2:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-2
    expose:
      - 4004
    command: settings-tp -vv --connect tcp://validator-2:4004

  settings-tp-3:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-3
    expose:
      - 4004
    command: settings-tp -vv --connect tcp://validator-3:4004

  settings-tp-4:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-4
    expose:
      - 4004
    command: settings-tp -vv --connect tcp://validator-4:4004

  pbft-0:
    image: hyperledger/sawtooth-pbft-engine:chime
    container_name: sawtooth-pbft-engine-default-0
    command: pbft-engine -vv --connect tcp://validator-0:5050

  pbft-1:
    image: hyperledger/sawtooth-pbft-engine:chime
    container_name: sawtooth-pbft-engine-default-1
    command: pbft-engine -vv --connect tcp://validator-1:5050

  pbft-2:
    image: hyperledger/sawtooth-pbft-engine:chime
    container_name: sawtooth-pbft-engine-default-2
    command: pbft-engine -vv --connect tcp://validator-2:5050

  pbft-3:
    image: hyperledger/sawtooth-pbft-engine:chime
    container_name: sawtooth-pbft-engine-default-3
    command: pbft-engine -vv --connect tcp://validator-3:5050

  pbft-4:
    image: hyperledger/sawtooth-pbft-engine:chime
    container_name: sawtooth-pbft-engine-default-4
    command: pbft-engine -vv --connect tcp://validator-4:5050

#  poet-engine-0:
#    image: hyperledger/sawtooth-poet-engine:1.1.3
#    container_name: sawtooth-poet-engine-0
#    depends_on:
#      - validator-0
#    volumes:
#      - volume-shared:/volume-shared
#    command: "bash -c \"\
#        if [ ! -f /volume-shared/poet-enclave-measurement ]; then \
#            poet enclave measurement >> /volume-shared/poet-enclave-measurement; \
#        fi && \
#        if [ ! -f /volume-shared/poet-enclave-basename ]; then \
#            poet enclave basename >> /volume-shared/poet-enclave-basename; \
#        fi && \
#        if [ ! -f /volume-shared/simulator_rk_pub.pem ]; then \
#            cp /etc/sawtooth/simulator_rk_pub.pem /volume-shared; \
#        fi && \
#        while [ ! -f /volume-shared/validator-0/keys/validator.priv ]; do sleep 1; done && \
#        cp -a /volume-shared/validator-0/keys /etc/sawtooth && \
#        poet registration create -k /etc/sawtooth/keys/validator.priv -o /volume-shared/poet.batch && \
#        poet-engine -vv -C tcp://validator-0:5050 --component tcp://validator-0:4004 \
#    \""
#
#  poet-engine-1:
#    image: hyperledger/sawtooth-poet-engine:1.1.3
#    container_name: sawtooth-poet-engine-1
#    depends_on:
#      - validator-1
#    volumes:
#      - volume-shared:/volume-shared
#    command: "bash -c \"\
#        while [ ! -f /volume-shared/validator-1/keys/validator.priv ]; do sleep 1; done && \
#        cp -a /volume-shared/validator-1/keys /etc/sawtooth && \
#        poet-engine -vv -C tcp://validator-1:5050 --component tcp://validator-1:4004 \
#    \""
#
#  poet-engine-2:
#    image: hyperledger/sawtooth-poet-engine:1.1.3
#    container_name: sawtooth-poet-engine-2
#    depends_on:
#      - validator-2
#    volumes:
#      - volume-shared:/volume-shared
#    command: "bash -c \"\
#        while [ ! -f /volume-shared/validator-2/keys/validator.priv ]; do sleep 1; done && \
#        cp -a /volume-shared/validator-2/keys /etc/sawtooth && \
#        poet-engine -vv -C tcp://validator-2:5050 --component tcp://validator-2:4004 \
#    \""
#
#  poet-engine-3:
#    image: hyperledger/sawtooth-poet-engine:1.1.3
#    container_name: sawtooth-poet-engine-3
#    depends_on:
#      - validator-3
#    volumes:
#      - volume-shared:/volume-shared
#    command: "bash -c \"\
#        while [ ! -f /volume-shared/validator-3/keys/validator.priv ]; do sleep 1; done && \
#        cp -a /volume-shared/validator-3/keys /etc/sawtooth && \
#        poet-engine -vv -C tcp://validator-3:5050 --component tcp://validator-3:4004 \
#    \""
#
#  poet-validator-registry-tp-0:
#    image: hyperledger/sawtooth-poet-validator-registry-tp:1.1.2
#    container_name: sawtooth-poet-validator-registry-tp-0
#    expose:
#      - 4004
#    command: poet-validator-registry-tp -vv -C tcp://validator-0:4004
#
#  poet-validator-registry-tp-1:
#    image: hyperledger/sawtooth-poet-validator-registry-tp:1.1.2
#    container_name: sawtooth-poet-validator-registry-tp-1
#    expose:
#      - 4004
#    command: poet-validator-registry-tp -vv -C tcp://validator-1:4004
#
#  poet-validator-registry-tp-2:
#    image: hyperledger/sawtooth-poet-validator-registry-tp:1.1.2
#    container_name: sawtooth-poet-validator-registry-tp-2
#    expose:
#      - 4004
#    command: poet-validator-registry-tp -vv -C tcp://validator-2:4004
#
#  poet-validator-registry-tp-3:
#    image: hyperledger/sawtooth-poet-validator-registry-tp:1.1.2
#    container_name: sawtooth-poet-validator-registry-tp-3
#    expose:
#      - 4004
#    command: poet-validator-registry-tp -vv -C tcp://validator-3:4004

  sawtooth-rest-api-0:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-0
    expose:
      - 8008
    ports:
      - '8043:8008'
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator-0:4004
        --bind sawtooth-rest-api-0:8008

  sawtooth-rest-api-1:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-1
    expose:
      - 8008
    ports:
      - '8143:8008'
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator-1:4004
        --bind sawtooth-rest-api-1:8008

  sawtooth-rest-api-2:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-2
    expose:
      - 8008
    ports:
      - '8243:8008'
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator-2:4004
        --bind sawtooth-rest-api-2:8008

  sawtooth-rest-api-3:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-3
    expose:
      - 8008
    ports:
      - '8343:8008'
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator-3:4004
        --bind sawtooth-rest-api-3:8008

  sawtooth-rest-api-4:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-4
    expose:
      - 8008
    ports:
      - '8443:8008'
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator-4:4004
        --bind sawtooth-rest-api-4:8008

  validator-0:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-0
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - volume-shared:/volume-shared
    command:
      - bash
      - -c
      - |
        if [ ! -f /volume-shared/network_status_0.txt ]; then
          echo '--- First run setup started... ---\n'
          sawadm keygen --force
          mkdir -p /volume-shared/validator-0 || true
          cp -a /etc/sawtooth/keys /volume-shared/validator-0/
          echo '--- Generate genesis ... ---\n'
          sawset genesis -k /etc/sawtooth/keys/validator.priv -o config-genesis.batch
          echo '--- Wait for pub files ... ---\n'
          while [[ ! -f /volume-shared/validator-1/keys/validator.pub ||
                   ! -f /volume-shared/validator-2/keys/validator.pub ||
                   ! -f /volume-shared/validator-3/keys/validator.pub ||
                   ! -f /volume-shared/validator-4/keys/validator.pub ]];
          do sleep 1; ls -l /volume-shared; done;
          echo "sawtooth.consensus.pbft.members=[\"$$(cat /volume-shared/validator-0/keys/validator.pub)\",\"$$(cat /volume-shared/validator-1/keys/validator.pub)\",\"$$(cat /volume-shared/validator-2/keys/validator.pub)\",\"$$(cat /volume-shared/validator-3/keys/validator.pub)\",\"$$(cat /volume-shared/validator-4/keys/validator.pub)\"]"
          echo '--- Create proposal ... ---\n';
          sawset proposal create -k /etc/sawtooth/keys/validator.priv \
            sawtooth.consensus.algorithm.name=pbft \
            sawtooth.consensus.algorithm.version=0.1 \
            sawtooth.consensus.pbft.members="[\"$$(cat /volume-shared/validator-0/keys/validator.pub)\",\"$$(cat /volume-shared/validator-1/keys/validator.pub)\",\"$$(cat /volume-shared/validator-2/keys/validator.pub)\",\"$$(cat /volume-shared/validator-3/keys/validator.pub)\",\"$$(cat /volume-shared/validator-4/keys/validator.pub)\"]" \
            sawtooth.publisher.max_batches_per_block=1200 \
            -o config.batch
          sawadm genesis config-genesis.batch config.batch
          echo Done > /volume-shared/network_status_0.txt
          echo '--- First run setup completed... ---\n'
        else
          echo '--- First run setup skipped... ---\n'
        fi
        sawtooth-validator -vv \
          --bind network:tcp://eth0:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --endpoint tcp://validator-0:8800 \
          --peering static \
          --scheduler parallel \
          --maximum-peer-connectivity 10000 \
          --network-auth trust

#    command: |
#      bash -c "
#        if [ ! -f /volume-shared/network_status_0.txt ]; then \
#          echo '--- First run setup started... ---\n'; \
#          sawadm keygen --force; \
#          mkdir -p /volume-shared/validator-0 || true; \
#          cp -a /etc/sawtooth/keys /volume-shared/validator-0/ ; \
#          echo '--- Generate genesis ... ---\n'; \
#          sawset genesis \
#            -k /etc/sawtooth/keys/validator.priv \
#            -o config-genesis.batch ; \
#          echo '--- Wait for pub files ... ---\n'; \
#          while [[ ! -f /volume-shared/validator-1/keys/validator.pub || \
#                   ! -f /volume-shared/validator-2/keys/validator.pub || \
#                   ! -f /volume-shared/validator-3/keys/validator.pub ]];
#          do sleep 1; ls -l /volume-shared; done; \
#          # echo "\"'$$(cat /volume-shared/validator-0/keys/validator.pub)'\"" > /volume-shared/node_0_public_key.txt ; \
#
#          echo "\"" > /volume-shared/node_0_public_key.txt ; \
#          echo $$(cat /volume-shared/validator-0/keys/validator.pub) > /volume-shared/node_0_public_key.txt ; \
#          echo "\"" > /volume-shared/node_0_public_key.txt ; \
#          echo $$(cat /volume-shared/node_0_public_key.txt) ; \
#
#          echo sawtooth.consensus.pbft.members=\\'[\"$$(cat /volume-shared/validator-0/keys/validator.pub)\",\"'$$(cat /volume-shared/validator-1/keys/validator.pub)'\",\"'$$(cat /volume-shared/validator-2/keys/validator.pub)'\",\"'$$(cat /volume-shared/validator-3/keys/validator.pub)'\"]\\' ; \
#          echo '--- Create proposal ... ---\n'; \
#          sawset proposal create \
#            -k /etc/sawtooth/keys/validator.priv \
#            sawtooth.consensus.algorithm.name=pbft \
#            sawtooth.consensus.algorithm.version=0.1 \
#            sawtooth.consensus.pbft.members=\\[\"'$$(cat /volume-shared/validator-0/keys/validator.pub)'\",\"'$$(cat /volume-shared/validator-1/keys/validator.pub)'\",\"'$$(cat /volume-shared/validator-2/keys/validator.pub)'\",\"'$$(cat /volume-shared/validator-3/keys/validator.pub)'\"\\] \
#            sawtooth.publisher.max_batches_per_block=1200 \
#            -o config.batch ; \
#          sawadm genesis \
#            config-genesis.batch config.batch ; \
#          # echo Done > /volume-shared/network_status_0.txt ; \
#          echo '--- First run setup completed... ---\n' ; \
#        else \
#          echo '--- First run setup skipped... ---\n' ; \
#        fi && \
#        sawtooth-validator -v \
#          --bind network:tcp://eth0:8800 \
#          --bind component:tcp://eth0:4004 \
#          --bind consensus:tcp://eth0:5050 \
#          --endpoint tcp://validator-0:8800 \
#          --peering static \
#          --scheduler serial \
#          --maximum-peer-connectivity 10000 \
#          --network-auth trust
#      "

  xo-tp-python-0:
    image: hyperledger/sawtooth-xo-tp-python:chime
    container_name: sawtooth-xo-tp-python-default-0
    entrypoint: xo-tp-python -vv -C tcp://validator-0:4004

  xo-tp-python-1:
    image: hyperledger/sawtooth-xo-tp-python:chime
    container_name: sawtooth-xo-tp-python-default-1
    entrypoint: xo-tp-python -vv -C tcp://validator-1:4004

  xo-tp-python-2:
    image: hyperledger/sawtooth-xo-tp-python:chime
    container_name: sawtooth-xo-tp-python-default-2
    entrypoint: xo-tp-python -vv -C tcp://validator-2:4004

  xo-tp-python-3:
    image: hyperledger/sawtooth-xo-tp-python:chime
    container_name: sawtooth-xo-tp-python-default-3
    entrypoint: xo-tp-python -vv -C tcp://validator-3:4004

  xo-tp-python-4:
    image: hyperledger/sawtooth-xo-tp-python:chime
    container_name: sawtooth-xo-tp-python-default-4
    entrypoint: xo-tp-python -vv -C tcp://validator-4:4004

  intkey-tp-python-0:
    image: hyperledger/sawtooth-intkey-tp-python:chime
    container_name: sawtooth-intkey-tp-python-0
    expose:
      - 4004
    entrypoint: intkey-tp-python -vv -C tcp://validator-0:4004

  intkey-tp-python-1:
    image: hyperledger/sawtooth-intkey-tp-python:chime
    container_name: sawtooth-intkey-tp-python-1
    expose:
      - 4004
    entrypoint: intkey-tp-python -vv -C tcp://validator-1:4004

  intkey-tp-python-2:
    image: hyperledger/sawtooth-intkey-tp-python:chime
    container_name: sawtooth-intkey-tp-python-2
    expose:
      - 4004
    entrypoint: intkey-tp-python -vv -C tcp://validator-2:4004

  intkey-tp-python-3:
    image: hyperledger/sawtooth-intkey-tp-python:chime
    container_name: sawtooth-intkey-tp-python-3
    expose:
      - 4004
    entrypoint: intkey-tp-python -vv -C tcp://validator-3:4004

  intkey-tp-python-4:
    image: hyperledger/sawtooth-intkey-tp-python:chime
    container_name: sawtooth-intkey-tp-python-4
    expose:
      - 4004
    entrypoint: intkey-tp-python -vv -C tcp://validator-4:4004

  validator-1:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-1
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - volume-shared:/volume-shared
    command: |
      bash -c "
        if [ ! -f /volume-shared/network_status_1.txt ]; then
          echo '--- First run setup started... ---\n' && \
          sawadm keygen --force && \
          mkdir -p /volume-shared/validator-1 || true && \
          cp -a /etc/sawtooth/keys /volume-shared/validator-1/ && \
          echo Done > /volume-shared/network_status_1.txt && \
          echo '--- First run setup completed... ---\n'
        else
          echo '--- First run setup skipped... ---\n'
        fi;
        sawtooth-validator -vv \
            --bind network:tcp://eth0:8800 \
            --bind component:tcp://eth0:4004 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --endpoint tcp://validator-1:8800 \
            --peers tcp://validator-0:8800 \
            --scheduler parallel \
            --maximum-peer-connectivity 10000 \
            --network-auth trust
      "


  validator-2:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-2
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - volume-shared:/volume-shared
    command: |
      bash -c "
        if [ ! -f /volume-shared/network_status_2.txt ]; then
          echo '--- First run setup started... ---\n' && \
          sawadm keygen --force && \
          mkdir -p /volume-shared/validator-2 && \
          cp -a /etc/sawtooth/keys /volume-shared/validator-2/ && \
          echo Done > /volume-shared/network_status_2.txt && \
          echo '--- First run setup completed... ---\n'
        else
          echo '--- First run setup skipped... ---\n'
        fi;
        sawtooth-validator -vv \
            --bind network:tcp://eth0:8800 \
            --bind component:tcp://eth0:4004 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --endpoint tcp://validator-2:8800 \
            --peers tcp://validator-0:8800 \
            --peers tcp://validator-1:8800 \
            --scheduler parallel \
            --maximum-peer-connectivity 10000 \
            --network-auth trust
      "

  validator-3:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-3
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - volume-shared:/volume-shared
    command: |
      bash -c "
        if [ ! -f /volume-shared/network_status_3.txt ]; then
          echo '--- First run setup started... ---\n' && \
          sawadm keygen --force && \
          mkdir -p /volume-shared/validator-3 && \
          cp -a /etc/sawtooth/keys /volume-shared/validator-3/ && \
          echo Done > /volume-shared/network_status_3.txt && \
          echo '--- First run setup completed... ---\n'
        else
          echo '--- First run setup skipped... ---\n'
        fi;
        sawtooth-validator -vv \
            --bind network:tcp://eth0:8800 \
            --bind component:tcp://eth0:4004 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --endpoint tcp://validator-3:8800 \
            --peers tcp://validator-0:8800 \
            --peers tcp://validator-1:8800 \
            --peers tcp://validator-2:8800 \
            --scheduler parallel \
            --maximum-peer-connectivity 10000 \
            --network-auth trust
      "

  validator-4:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-4
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - volume-shared:/volume-shared
    command: |
      bash -c "
        if [ ! -f /volume-shared/network_status_4.txt ]; then
          echo '--- First run setup started... ---\n' && \
          sawadm keygen --force && \
          mkdir -p /volume-shared/validator-4 && \
          cp -a /etc/sawtooth/keys /volume-shared/validator-4/ && \
          echo Done > /volume-shared/network_status_4.txt && \
          echo '--- First run setup completed... ---\n'
        else
          echo '--- First run setup skipped... ---\n'
        fi;
        sawtooth-validator -vv \
            --bind network:tcp://eth0:8800 \
            --bind component:tcp://eth0:4004 \
            --bind consensus:tcp://eth0:5050 \
            --peering static \
            --endpoint tcp://validator-4:8800 \
            --peers tcp://validator-0:8800 \
            --peers tcp://validator-1:8800 \
            --peers tcp://validator-2:8800 \
            --peers tcp://validator-3:8800 \
            --scheduler parallel \
            --maximum-peer-connectivity 10000 \
            --network-auth trust
      "

  shell:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""
